name: NukeBuildWithGithubActions

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Build
      shell: pwsh
      run: ./build.ps1 --target compile --verbosity verbose
    - name: Test
      shell: pwsh
      run: ./build.ps1 --target test --verbosity verbose
